#!/usr/bin/env bash
# Personal memory module — summarize recent Claude/Codex sessions every 30 min
# Uses LiteLLM-compatible API for summarization (reads from .env, never committed)

MEMORY_DIR="${WATCHDOG_HOME}/docs/memory/summaries"
BEST_PRACTICES_DIR="${WATCHDOG_HOME}/docs/memory/best-practices"
ENV_FILE="${WATCHDOG_HOME}/.env"

# Load API config from .env (NEVER committed to git)
load_api_config() {
    if [[ -f "$ENV_FILE" ]]; then
        export $(grep -v '^#' "$ENV_FILE" | grep -v '^$' | xargs)
    fi
    # Fallback to environment
    OPENAI_API_KEY="${OPENAI_API_KEY:-}"
    OPENAI_BASE_URL="${OPENAI_BASE_URL:-}"
    SUMMARY_MODEL="${SUMMARY_MODEL:-anthropic/claude-opus-4.6}"
}

# Call LLM API via curl
call_llm() {
    local prompt="$1"
    local max_tokens="${2:-1024}"
    [[ -z "$OPENAI_API_KEY" ]] && { log_warn "MEMORY: No API key, skip summarization"; return 1; }

    local response
    response=$(curl -s --max-time 30 \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${OPENAI_API_KEY}" \
        "${OPENAI_BASE_URL}/chat/completions" \
        -d "$(cat <<PAYLOAD
{
  "model": "${SUMMARY_MODEL}",
  "max_tokens": ${max_tokens},
  "messages": [
    {"role": "system", "content": "You are a concise technical summarizer. Output markdown. Focus on: what was asked, what was decided, key learnings. Keep under 500 words."},
    {"role": "user", "content": $(echo "$prompt" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))')}
  ]
}
PAYLOAD
)")

    # Extract content from response
    echo "$response" | python3 -c "
import json, sys
try:
    d = json.loads(sys.stdin.read())
    print(d['choices'][0]['message']['content'])
except Exception as e:
    print(f'(summarization failed: {e})')
" 2>/dev/null
}

# Extract recent questions/answers from Claude session files
extract_recent_claude_context() {
    local hours="${1:-1}"  # last N hours
    local cutoff
    cutoff=$(date -v-${hours}H +%s 2>/dev/null || date -d "${hours} hours ago" +%s 2>/dev/null || echo 0)

    local context=""
    find "$HOME/.claude/projects" -name '*.jsonl' -type f -newer /tmp/.watchdog-memory-marker 2>/dev/null | while read -r f; do
        python3 -c "
import json, sys
lines = open('$f').readlines()[-50:]  # last 50 messages
for line in lines:
    try:
        d = json.loads(line)
        role = d.get('type', d.get('role', ''))
        msg = d.get('message', {})
        content = msg.get('content', '') if isinstance(msg, dict) else str(msg)
        if isinstance(content, list):
            texts = [c.get('text','') for c in content if isinstance(c, dict) and c.get('type') == 'text']
            content = ' '.join(texts)
        if content and role in ('user', 'assistant'):
            text = str(content).strip()[:200]
            if text:
                print(f'[{role}] {text}')
    except: pass
" 2>/dev/null
    done
}

# Generate a 30-min summary
generate_summary() {
    load_api_config
    mkdir -p "$MEMORY_DIR"

    # Touch marker file for "last summarized" time
    local marker="/tmp/.watchdog-memory-marker"
    [[ ! -f "$marker" ]] && touch -t "$(date -v-30M '+%Y%m%d%H%M.%S')" "$marker" 2>/dev/null

    # Extract recent context
    local context
    context=$(extract_recent_claude_context 1)

    if [[ -z "$context" || ${#context} -lt 100 ]]; then
        log_debug "MEMORY: Not enough recent context to summarize"
        touch "$marker"
        return 0
    fi

    log_info "MEMORY: Generating 30-min summary..."

    local summary
    summary=$(call_llm "Summarize the following AI coding session activity from the last 30 minutes. Extract: (1) What questions were asked, (2) What decisions were made, (3) Key learnings or patterns discovered, (4) Any unresolved issues.

--- SESSION CONTEXT ---
$context
--- END ---

Output as a concise markdown summary with sections: Questions, Decisions, Learnings, Open Issues.")

    if [[ -n "$summary" && "$summary" != *"summarization failed"* ]]; then
        local ts
        ts=$(date '+%Y%m%d_%H%M')
        local outfile="${MEMORY_DIR}/${ts}.md"
        cat > "$outfile" <<EOF
# Session Summary — $(date '+%Y-%m-%d %H:%M')

$summary

---
_Generated by ai-watchdog memory module_
EOF
        log_info "MEMORY: Summary saved to $outfile"

        # Keep only last 48 summaries (24 hours at 30-min intervals)
        ls -t "${MEMORY_DIR}"/*.md 2>/dev/null | tail -n +49 | xargs rm -f 2>/dev/null
    else
        log_warn "MEMORY: Summarization returned empty or failed"
    fi

    touch "$marker"
}

# List recent summaries (for TUI/web)
list_recent_summaries() {
    local n="${1:-5}"
    ls -t "${MEMORY_DIR}"/*.md 2>/dev/null | head -"$n"
}

# List best practices files
list_best_practices() {
    ls "${BEST_PRACTICES_DIR}"/*.md 2>/dev/null
}
